name: Function Literal
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 4
excerpt_separator: <!-- more -->
description: Where I talk about code and stuff
url: http://llkats.github.io

permalink: /:year/:month/:day/:title
