name: Function Literal
markdown: redcarpet
highlighter: 'pygments'
paginate: 4
excerpt_separator: <!-- more -->
description: Where I talk about code and stuff
url: http://llkats.github.io

permalink: /:year/:month/:day/:title
